export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU';
export const NEXT_SECTION = 'NEXT_SECTION';
export const UPDATE_SAVING_GOAL_NAME = 'UPDATE_SAVING_GOAL_NAME';
export const UPDATE_SAVING_GOAL_VALUE = 'UPDATE_SAVING_GOAL_VALUE';
