CREATE DATABASE bujj_it;

CREATE TABLE users
(
  user_id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  username VARCHAR(255)NOT NULL,
  dob DATE NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL
);